# .github/workflows/deploy-dev.yml
name: Deploy Dev

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run my composite build action
        uses: ./.github/actions/react-build
