name: Deploy to S3

on:
  push:
    branches: [ master ]   

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::027814278268:role/GitHubActions-OIDC-Deploy
          aws-region: ap-south-1   # change to your AWS region

      - name: Sync files to S3
        run: aws s3 sync ./ s3://i-react-app --delete --exclude ".git/*" --exclude ".github/*"
